= Lab 15 - Refreshing Configuration with Spring Cloud Bus

[abstract]
--
The http://cloud.spring.io/spring-cloud-bus/[Spring Cloud Bus] links nodes in a distributed system with a lightweight message bus.
We'll use it, combined with a Spring bean scope called `@RefreshScope`, to broadcast configuration changes to our microservices.
The bus will be backed by a running instance of http://www.rabbitmq.com/[RabbitMQ].
--

== Adding the Cloud Bus to the Test Config Client

. Change to the lab directory:
+
----
$ cd $COURSE_HOME/day_02/session_06/lab_15/initial/springtrader-config-client
----
+
and import the project (via `pom.xml`) into your IDE of choice.

. In `pom.xml`, add a dependency on `spring-cloud-starter-bus-amqp`:
+
----
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
----

. In the package `io.springtrader.configclient`, create the class `Greeter` and paste in the following source code:
+
----
@Component
@RefreshScope
public class Greeter {

    @Value("${greeting}")
    private String greeting;

    public String getGreeting() {
        return greeting;
    }
}
----

. Edit `GreetingController`, replacing the injected value for `greeting` with an injected instance of `Greeter`.
Use that instance to obtain the greeting for the `greeter` request method.
You can paste the following code to accomplish this:
+
----
@RestController
public class GreetingController {

    @Autowired
    Greeter greeter;

    @RequestMapping("/")
    public String greeter() {
        return greeter.getGreeting() + " World!";
    }

}
----

. To run the application now, you'll need a local install of RabbitMQ. You can obtain one for your platform http://www.rabbitmq.com/download.html[here].

. A completed `springtrader-config-server` project has been placed in `$COURSE_HOME/day_02/session_06/lab_15/initial/springtrader-config-server` for your convenience.
In a different terminal window, change to that directory, rebuild, and run the application:
+
----
$ cd $COURSE_HOME/day_02/session_06/lab_15/initial/springtrader-config-server
$ mvn clean package
$ java -jar target/springtrader-config-server-0.0.1-SNAPSHOT.jar
----

. Build your new `springtrader-config-client`:
+
----
$ mvn clean package
----

. Run the application:
+
----
$ java -jar target/springtrader-config-client-0.0.1-SNAPSHOT.jar
----

. Use `curl` to access the application and make sure that everything is still working as before:
+
----
$ curl -i localhost:8080
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: demo
Content-Type: text/plain;charset=UTF-8
Content-Length: 12
Date: Wed, 06 Jan 2016 08:10:17 GMT

Hello World!
----

. In a separate terminal window, run another copy of the client on a different port to create a system of apps connected by the bus:
+
----
$ SERVER_PORT=8081 java -jar target/springtrader-config-client-0.0.1-SNAPSHOT.jar
----

. Use `curl` to access the second instance running on port `8081`:
+
----
$ curl -i localhost:8081
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: demo:8081
Content-Type: text/plain;charset=UTF-8
Content-Length: 12
Date: Wed, 06 Jan 2016 08:12:02 GMT

Hello World!
----

. Now, open `demo.yml` from your config-repo and change the greeting:
+
----
greeting: Ohai
----

. Stage, commit, and push your changes:
+
----
git add . && git commit -m "swap greeting" && git push origin master
----

. Using `curl`, test and see that the config server has updated with your new greeting:
+
----
$ curl -i localhost:8888/demo/default
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: bootstrap:8888
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 06 Jan 2016 08:13:00 GMT

{
	"name":"default",
	"label":"",
	"propertySources":
	[
		{"name":"https://github.com/caxqueiroz/springtrader-config-repo.git/demo.yml",
		"source":{"greeting":"Ohai"}
	},
		{"name":"https://github.com/caxqueiroz/springtrader-config-repo.git/application.yml",
		"source":{"configserver":true}
	}
	]
}
----

. Using `curl`, show that the greeting *has not* refreshed in the client applications:
+
----
$ curl -i localhost:8080
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: demo
Content-Type: text/plain;charset=UTF-8
Content-Length: 12
Date: Wed, 06 Jan 2016 08:14:27 GMT

Hello World!

$ curl -i localhost:8081
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: demo:8081
Content-Type: text/plain;charset=UTF-8
Content-Length: 12
Date: Wed, 06 Jan 2016 08:14:52 GMT

Hello World!
----

. Now, `POST` a request to the `/bus/refresh` endpoint to trigger a configuration refresh event:
+
----
$ curl -i -X POST localhost:8080/bus/refresh
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: demo
Content-Length: 0
Date: Wed, 06 Jan 2016 08:15:58 GMT
----

. Using `curl`, show that the greeting *has* now refreshed in the client applications:
+
----
$ curl -i localhost:8080
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: demo
Content-Type: text/plain;charset=UTF-8
Content-Length: 11
Date: Wed, 06 Jan 2016 08:16:19 GMT

Ohai World!

$ curl -i localhost:8081
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: demo:8081
Content-Type: text/plain;charset=UTF-8
Content-Length: 11
Date: Wed, 06 Jan 2016 08:16:32 GMT

Ohai World!
----

== Update the Microservices to Use the Cloud Bus

. Create a Pivotal RabbitMQ service to back the Cloud Bus:
+
----
$ cf cs p-rabbitmq standard springtrader-cloud-bus-amqp
Creating service instance springtrader-cloud-bus-amqp in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK
----
+

. In your config repo, update the file `application.yml`, adding a new property:
+
----
configserver: true
bus: false
----
+
We'll use the refresh of this property in each of our microservices' environments to verify that the cloud bus is working.

. Stage, commit, and push your changes:
+
----
git add . && git commit -m "add bus property" && git push origin master
----

. Access the config server using `curl` to make sure the new property exists:
+
----
$ curl -i springtrader-config-server-succinct-electronarcosis.cfapps.pez.pivotal.io/application/default
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Jan 2016 02:20:19 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-config-server:cloud:8080
X-Cf-Requestid: b5c59a87-e45b-4545-4333-93227b677a20
Content-Length: 178
Connection: close

{
	"name":"default",
	"label":"",
	"propertySources":[
		{
			"name":"https://github.com/caxqueiroz/springtrader-config-repo.git/application.yml",
			"source":{
						"configserver":true,
						"bus":false
			}
		}
	]
}
----

Each of the three microservice projects has been copied into `$COURSE_HOME/day_02/session_06/lab_15/initial`, and are in the state we left them at the end of link:../lab_14/lab_14.adoc[Lab 14].
You can either continue your existing projects or pickup from these copies.

For each project, perform the following steps (we'll do these once for the `springtrader-quotes` project in this guide):

. In `pom.xml`, add a dependency on `spring-cloud-starter-bus-amqp`:
+
----
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-bus-amqp</artifactId>
  <version>1.0.3.RELEASE</version>
</dependency>
----

. In `manifest.yml`, add a binding to `springtrader-cloud-bus-amqp`:
+
----
---
timeout: 180
instances: 1
memory: 1G
env:
    SPRING_PROFILES_ACTIVE: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: springtrader-quotes
  random-route: true
  path: target/quotes-1.0.0-SNAPSHOT.jar
  services: [ springtrader-quotes-db, springtrader-config-service, springtrader-cloud-bus-amqp ] # <-- ADD THIS!
----
. In `application.yml`, add:
+
----
spring:
	rabbitmq:
		addresses: ${vcap.services.springtrader-cloud-bus-amqp.credentials.uri:amqp://${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}}
----
. Build the JAR:
+
----
$ mvn package
----

. Push the application:
+
----
$ cf push

...

Showing health and status for app springtrader-quotes in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: springtrader-quotes-untrafficked-iodism.cfapps.pez.pivotal.io
last uploaded: Mon Jan 11 02:39:17 UTC 2016
stack: cflinuxfs2
buildpack: java-buildpack=v3.3.1-offline-https://github.com/cloudfoundry/java-buildpack.git#063836b java-main java-opts open-jdk-like-jre=1.8.0_65 open-jdk-like-memory-calculator=2.0.0_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE

     state     since                    cpu    memory         disk           details
#0   running   2016-01-11 10:40:05 AM   0.0%   520.1M of 1G   144.3M of 1G
----

. Verify the existence of our new `bus` property using `curl`:
+
----
curl -i curl -i springtrader-quotes-unrefining-peanuts.cfapps.pez.pivotal.io/env
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Jan 2016 06:31:40 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-quotes:cloud:0
X-Cf-Requestid: f24371d6-73de-4153-7990-235760316ed0
Connection: close
Transfer-Encoding: chunked

{

...

"configService:https://github.com/caxqueiroz/springtrader-config-repo.git/application.yml": {
  "bus": false,
  "configserver": true
},

...

}
----

Once you've completed these steps for all three microservices, we'll update the `bus` property to `true` and trigger a refresh across all three applications.

. Open `application.yml` from your config-repo and change the `bus` property to true:
+
----
configserver: true
bus: true
----

. Stage, commit, and push your changes:
+
----
git add . && git commit -m "change bus to true" && git push origin master
----

. Using `curl`, test and see that the config server has updated with your new greeting:
+
----
curl -i springtrader-config-server-succinct-electronarcosis.cfapps.pez.pivotal.io/application/default
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Jan 2016 06:38:11 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-config-server:cloud:8080
X-Cf-Requestid: f4329f45-e8e2-4fee-692c-efeb00ad1a5a
Content-Length: 177
Connection: close

{
    "label": "",
    "name": "default",
    "propertySources": [
        {
            "name": "https://github.com/caxqueiroz/springtrader-config-repo.git/application.yml",
            "source": {
                "bus": true,
                "configserver": true
            }
        }
    ]
}
----

. Using `curl`, `POST` a refresh event to the `springtrader-quotes` service:
+
----
$ curl -i -X POST springtrader-quotes-hallucal-splitter.cfapps.pez.pivotal.io/bus/refresh
TTP/1.1 200 OK
Content-Length: 0
Date: Mon, 11 Jan 2016 07:38:45 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-quotes:cloud:0
X-Cf-Requestid: 7800e32f-da68-4df3-6cfc-8912003e6ac4
Content-Type: text/plain; charset=utf-8
Connection: close
----

. Using `curl`, verify that `bus` has updated to `true` across all services:
+
----
$ curl -i springtrader-quotes-hallucal-splitter.cfapps.pez.pivotal.io/env
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Jan 2016 07:39:50 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-quotes:cloud:0
X-Cf-Requestid: 563501ac-e471-46c3-58d1-40f485b870dd
Connection: close
Transfer-Encoding: chunked

{

...

"configService:https://github.com/caxqueiroz/springtrader-config-repo.git/application.yml": {
  "bus": true,
  "configserver": true
},

...

}

----
