:compat-mode:
= Lab 11 - Build a Quotes services using MongoDB

[abstract]
--
In this lab we'll begin the first subproject of our complete cloud-native application architecture: _SpringTrader_, which implements the quotes fetching portion of a ``Trading-like'' application.
This microservice will provide the _Quotes Service_, which will allow us to search for companies and symbols in order to make transactions.

We'll be using the http://dev.markitondemand.com[MarketItOnDemad] API, and we'll model it's `Quote` and `Company` as a Stock concept in this microservice.
--

NOTE: The completed code for this lab can be found at `$COURSE_HOME/day_01/session_05/lab_11/complete/springtrader-quotes`.


== Developing the Service

. Change to the lab directory:
+
----
$ cd $COURSE_HOME/day_01/session_05/lab_11/initial/springtrader-quotes
----
+
and import the project (via `pom.xml`) into your IDE of choice.


. Create the package `io.pivotal.springtrader.quotes.domain` and in that package create the class `Stock`. Into that file you can paste the following source code, which models the MarketItOnDemand `Company` and `Quote` concepts:
+
----

@Document(collection="Stocks")
public class Stock {

    @Id
    @JsonProperty("Symbol")
    private String symbol;

    @Indexed(expireAfterSeconds = 60)
    @LastModifiedDate
    @JsonIgnore
    private DateTime lastModifiedDate;

    @Indexed()
    @JsonProperty("Name")
    private String companyName;

    @JsonProperty("Exchange")
    private String exchange;

    @JsonProperty("Status")
    private String status;

    @JsonProperty("LastPrice")
    private Double lastPrice;

    @JsonProperty("Change")
    private Double change;

    @JsonProperty("ChangePercent")
    private Double changePercent;

    @JsonProperty("Timestamp")
    @JsonFormat(shape= JsonFormat.Shape.STRING, pattern="EEE MMM dd HH:mm:ss zzzXXX yyyy", locale="ENGLISH")
    private Date timestamp;

    @JsonProperty("MSDate")
    private Double mSDate;

    @JsonProperty("MarketCap")
    private Double marketCap;

    @JsonProperty("Volume")
    private Integer volume;

    @JsonProperty("ChangeYTD")
    private Double changeYTD;

    @JsonProperty("ChangePercentYTD")
    private Double changePercentYTD;

    @JsonProperty("High")
    private Double high;

    @JsonProperty("Low")
    private Double low;

    @JsonProperty("Open")
    private Double open;

    public DateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getExchange() {
        return exchange;
    }

    public void setExchange(String exchange) {
        this.exchange = exchange;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Double getLastPrice() {
        return lastPrice;
    }

    public void setLastPrice(Double lastPrice) {
        this.lastPrice = lastPrice;
    }

    public Double getChange() {
        return change;
    }

    public void setChange(Double change) {
        this.change = change;
    }

    public Double getChangePercent() {
        return changePercent;
    }

    public void setChangePercent(Double changePercent) {
        this.changePercent = changePercent;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public Double getmSDate() {
        return mSDate;
    }

    public void setmSDate(Double mSDate) {
        this.mSDate = mSDate;
    }

    public Double getMarketCap() {
        return marketCap;
    }

    public void setMarketCap(Double marketCap) {
        this.marketCap = marketCap;
    }

    public Integer getVolume() {
        return volume;
    }

    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    public Double getChangeYTD() {
        return changeYTD;
    }

    public void setChangeYTD(Double changeYTD) {
        this.changeYTD = changeYTD;
    }

    public Double getChangePercentYTD() {
        return changePercentYTD;
    }

    public void setChangePercentYTD(Double changePercentYTD) {
        this.changePercentYTD = changePercentYTD;
    }

    public Double getHigh() {
        return high;
    }

    public void setHigh(Double high) {
        this.high = high;
    }

    public Double getLow() {
        return low;
    }

    public void setLow(Double low) {
        this.low = low;
    }

    public Double getOpen() {
        return open;
    }

    public void setOpen(Double open) {
        this.open = open;
    }

    @Override
    public String toString() {
        return "Stock{" +
                "symbol='" + symbol + '\'' +
                ", companyName='" + companyName + '\'' +
                ", exchange='" + exchange + '\'' +
                ", status='" + status + '\'' +
                ", lastPrice=" + lastPrice +
                ", change=" + change +
                ", changePercent=" + changePercent +
                ", timestamp=" + timestamp +
                ", mSDate=" + mSDate +
                ", marketCap=" + marketCap +
                ", volume=" + volume +
                ", changeYTD=" + changeYTD +
                ", changePercentYTD=" + changePercentYTD +
                ", high=" + high +
                ", low=" + low +
                ", open=" + open +
                '}';
    }
}
----
+
Notice that we're using Json annotations on the class and its fields. You'll need to use your IDE's features to add the appropriate import statements.
This class won't compile just yet, and we'll fix that in the next step.

+
Once again, use the IDE to add the appropriate import statements.
At this point, `Stock` should compile.

. Create the package `io.springtrader.quotes.repositories` and in that package create the interface `StockRepository`. Paste the following code and add appropriate imports:
+
----
@Repository
public interface StockRepository extends MongoRepository<Stock, String>{

    List<Stock> findByCompanyNameLike(String companyName);
}
----

. Create the package `io.springtrader.quotes.services` and in that package create the interface `QuoteService`. Paste the following code and add appropriate imports:
+
----
@Service
public class QuoteService {


    private static final Logger logger = LoggerFactory.getLogger(QuoteService.class);

    @Value("${api.url.company}")
    private String companyUrl = "http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input={name}";

    @Value("${api.url.quote}")
    private String quoteUrl = "http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol={symbol}";


    private RestOperations restOperations = new RestTemplate();

    private StockRepository stockRepository;


    @Autowired
    public void setStockRepository(StockRepository stockRepository) {
        this.stockRepository = stockRepository;
    }

    public Stock getQuote(String symbol) throws Exception {
        logger.debug("QuoteService.getQuote: retrieving quote for: " + symbol);

        symbol = symbol.toUpperCase();
        Stock stock = stockRepository.findOne(symbol);

        //what's happen if a stock has no info about its quotes?
        if (stock == null || stock.getStatus() == null) {
            stock = createStock(symbol);
            stock = stockRepository.save(stock);
        }


        return stock;

    }

    private Stock createStock(String symbol) throws SymbolNotFoundException {

        Stock returnedStock;

        try {

            Map<String, String> params = new HashMap<>();
            params.put("symbol", symbol);
            returnedStock = restOperations.getForObject(quoteUrl, Stock.class, params);
            logger.debug("QuoteService.getQuote: retrieved quote: " + returnedStock);

            Stock stock = companiesByNameOrSymbol(symbol)
                    .stream()
                    .filter(s -> s.getSymbol()
                            .equalsIgnoreCase(symbol))
                    .findFirst().orElse(new Stock());

            if (stock.getSymbol() == null) throw new SymbolNotFoundException("Symbol not found: " + symbol);
            returnedStock.setName(stock.getName());
            returnedStock.setExchange(stock.getExchange());

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            throw e;
        }
        return returnedStock;
    }

    public List<Stock> companiesByNameOrSymbol(String name) {
        logger.debug("QuoteService.companiesByNameOrSymbol: retrieving info for: " + name);
        List<Stock> stockList = new ArrayList<>();
        try {

            //only search for name.
            stockList = stockRepository.findByNameLike(name);
            if (stockList.size() > 0) return stockList;

            Map<String, String> params = new HashMap<>();
            params.put("name", name);
            Map[] companies = restOperations.getForObject(companyUrl, Map[].class, params);


            for (Map<String, String> company : companies) {
                Stock stock = new Stock();
                stock.setName(company.get("Name"));
                stock.setExchange(company.get("Exchange"));
                stock.setSymbol(company.get("Symbol"));
                stockList.add(stock);
            }

            logger.debug("QuoteService.companiesByNameOrSymbol: retrieved info: " + stockList);


        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        }

        return stockList;
    }
}
----

. Create the package `io.springtrader.quotes.controllers` and in that package create the class `QuoteController`. Paste the following code and add appropriate imports:
+
----
@RestController
public class QuoteController {

	private static final Logger logger = LoggerFactory.getLogger(QuoteController.class);

	/**
	 * The quoteService to delegate calls to.
	 */
	@Autowired
	private QuoteService quoteService;

	/**
	 * Retrives the current quote for the given symbol.
	 *
	 * @param symbol The symbol to retrieve the quote for.
	 * @return The Stock
	 * @throws SymbolNotFoundException if the symbol is not valid.
	 */
	@RequestMapping(value = "/quote/{symbol}", method = RequestMethod.GET)
	public ResponseEntity<Stock> getQuote(@PathVariable("symbol") final String symbol) throws Exception {
		logger.debug("QuoteController.getQuote: retrieving quote for: " + symbol);
		Stock stock = quoteService.getQuote(symbol);
		logger.info(String.format("Retrieved symbol: %s with quote %s", symbol, stock));
		return new ResponseEntity<>(stock, getNoCacheHeaders(), HttpStatus.OK);
	}

	/**
	 * Searches for companies that have a name or symbol matching the parameter.
	 *
	 * @param name The name or symbol to search for.
	 * @return The list of companies that match the search parameter.
	 */
	@RequestMapping(value = "/company/{name}", method = RequestMethod.GET)
	public ResponseEntity<List<Stock>> getCompanies(@PathVariable("name") final String name) {
		logger.debug("QuoteController.getCompanies: retrieving companies for: " + name);
		List<Stock> companies = quoteService.companiesByNameOrSymbol(name);
		logger.info(String.format("Retrieved companies with search parameter: %s - list: {}", name), companies);
		return new ResponseEntity<>(companies, HttpStatus.OK);
	}

	/**
	 * Generates HttpHeaders that have the no-cache set.
	 * @return HttpHeaders.
	 */
	private HttpHeaders getNoCacheHeaders() {
		HttpHeaders responseHeaders = new HttpHeaders();
		responseHeaders.set("Cache-Control", "no-cache");
		return responseHeaders;
	}

	/**
	 * Handles the response to the client if there is any exception during the processing of HTTP requests.
	 *
	 * @param e The exception thrown during the processing of the request.
	 * @param response The HttpResponse object.
	 * @throws IOException
	 */
	@ExceptionHandler({Exception.class})
	public void handleException(Exception e, HttpServletResponse response) throws IOException {
		logger.error("Handle Error: " + e.getMessage());
		response.sendError(HttpStatus.BAD_REQUEST.value(), "ERROR: " + e.getMessage());
	}
}
----

. Create the package `io.springtrader.quotes.config`, in it create the class `MongoLocalConfig`. This class represents the local configuration for MongoDB access. In this case, we will use an in-memory mongodb-like database (fongo).
Paste the following code and add appropriate imports:
+
----
@Configuration
@Profile("local") // <-- local profile. To run on local laptop
@EnableMongoAuditing // <-- Used to update lastmodifieddate field every time a document changes. 
@EnableMongoRepositories(basePackages = {"io.pivotal.springtrader.quotes"})
public class MongoLocalConfig extends AbstractMongoConfiguration{

    @Bean
    public MongoTemplate mongoTemplate(MongoDbFactory mongoDbFactory) {
        return new MongoTemplate(mongoDbFactory);
    }

    @Override
    protected String getDatabaseName() {
        return "Stocks";
    }

    @Override
    public Mongo mongo() throws Exception {
        Fongo fongo = new Fongo("mongo server 1");
        return fongo.getMongo();
//        return new MongoClient("localhost", 27017); <-- If you want to connect to a local mongodb. 
    }

    @Override
    protected String getMappingBasePackage() {
        return "io.pivotal.springtrader.quotes.domain";
    }
}
----

. Take a look at `src/main/resources/data.json`, which has already been provided in your project.
It contains a stocks dataset to be imported that we'll be using (excerpt here):
+
----
{"LastPrice": 9.77, "Volume": 2000, "MSDate": 42312, "Low": 9.77, "Timestamp": "Wed Nov 4 00:00:00 UTC-05:00 2015",
 "Open": 9.77, "Change": -0.0500000000000007, "ChangePercent": -0.509164969450109, "Exchange": "NASDAQ", "ChangeYTD": 9.4,
  "Status": "SUCCESS", "CompanyName": "1347 Capital Corp.", "MarketCap": 58111960,
  "Symbol": "TFSC", "ChangePercentYTD": 3.93617021276595, "High": 9.77}
----

. Build the JAR:
+
----
$ mvn clean package
----

. Run the application:
+
----
$ java -jar target/quotes-1.0.0-SNAPSHOT.jar
----

. Access the application using `curl` to make sure everything is working properly:
+
----
$ curl -i localhost:8086/quote/msft
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Date: Mon, 30 Nov 2015 10:51:36 GMT
Server: Apache-Coyote/1.1
X-Application-Context: quotes:cloud:0
X-Cf-Requestid: a5fc51f7-de23-47e1-5459-d56508826bb8
Content-Length: 365
Connection: close

{"Symbol":"MSFT","Name":"Microsoft Corp","Exchange":"NASDAQ","Status":"SUCCESS","LastPrice":53.95,
"Change":0.260000000000005,"ChangePercent":0.484261501210663,"Timestamp":"Fri Nov 27 17:59:00 GMTZ 2015",
"MSDate":42335.5409722222,"MarketCap":4.3094790635E11,"Volume":716782,"ChangeYTD":46.45,
"ChangePercentYTD":16.1463939720129,"High":54.08,"Low":53.81,"Open":53.94}
----

== Preparing for Cloud Foundry

. We want to bind to a MongoDB data source when running on Cloud Foundry, so let's create one:
+
----
$ cf cs p-mongodb development springtrader-quotes-db
Creating service pringtrader-quotes-db in org cqueiroz-pivot / space development as cqueiroz@pivotal.io...
OK
----

. Add the appropriate dependencies for MongoDB's driver and the Spring Cloud Connectors:
+
----
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-data-mongodb</artifactId>
</dependency>
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-spring-service-connector</artifactId>
   <version>1.2.0.RELEASE</version>
</dependency>
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-cloudfoundry-connector</artifactId>
   <version>1.2.0.RELEASE</version>
</dependency>		
----

.  Rename `src/main/resources/application.properties` file to `src/main/resources/application.yml` file.
YAML files make it much easier to represent multiple Spring profiles.
This will allow us to run locally with MongoDB locally and on CloudFoundry and when doing tests run Fongo (a java version of MongoDB).

. Paste the following into `application.yml`:
+
----
spring:
  profiles.active: local
  application:
     name: quotes

security:
  basic:
    enabled: false

expiration:
  time: -1 # enable offline mode. no expiration.

---
spring:
  profiles: local
server:
  port: 8086
---
spring:
  profiles: cloud
---
api:
 url:
   company: http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input={name}
   quote: http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol={symbol}
----

. Rebuild the JAR:
+
----
$ mvn clean package
----

== Deploying to Cloud Foundry

. Create an application manifest in `manifest.yml`:
+
[source,yml]
----
timeout: 180
instances: 1
memory: 512M
env:
    SPRING_PROFILES_ACTIVE: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: quotes
  random-route: true
  path: target/quotes-1.0.0-SNAPSHOT.jar
  services: [ springtrader-quotes-db ]
----

. Push to Cloud Foundry:
+
----
$ cf push

...

Showing health and status for app quotes in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 512M x 1 instances
urls: quotes-undespising-lenition.cfapps.pez.pivotal.io
last uploaded: Mon Dec 7 22:17:58 UTC 2015
stack: cflinuxfs2
buildpack: java-buildpack=v3.3.1-offline-https://github.com/cloudfoundry/java-buildpack.git#063836b java-main java-opts open-jdk-like-jre=1.8.0_65 open-jdk-like-memory-calculator=2.0.0_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE

     state     since                    cpu    memory           disk           details
#0   running   2015-12-07 07:18:48 PM   3.7%   367.2M of 512M   140.2M of 1G
----

. Access the application using `curl` at the random route provided by CF:
+
----
$ curl -i curl -i quotes-undespising-lenition.cfapps.pez.pivotal.io/quote/aapl
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Date: Mon, 07 Dec 2015 22:20:11 GMT
Server: Apache-Coyote/1.1
X-Application-Context: quotes:cloud:0
X-Cf-Requestid: 74a6092b-a1e4-4995-6a19-97398840309d
Content-Length: 367
Connection: close

{"Symbol":"AAPL","Name":"Apple Inc.","Exchange":"NASDAQ","Status":"SUCCESS",
"LastPrice":117.82,"Change":-0.210000000000008,"ChangePercent":-0.177920867576047,
"Timestamp":"Fri Nov 27 17:59:00 GMTZ 2015","MSDate":42335.5409722222,"MarketCap":6.5688549842E11,
"Volume":859197,"ChangeYTD":110.38,"ChangePercentYTD":6.74035151295524,"High":118.41,"Low":117.6,"Open":118.27}
----
