:compat-mode:
= Lab 10 - Leveraging Spring Cloud Connectors for Service Binding

In this lab we'll bind our RESTful web service from link:../lab_09/lab_09.adoc[Lab 9] to a MySQL database and leverage Spring Cloud Connectors to easily connect to it.

NOTE: The completed code for this lab can be found at `$COURSE_HOME/day_01/session_03/lab_10/complete/quotes`.

== Using Spring Cloud Connectors

. Change to the lab directory (the initial state for this lab is the same as the completed state for link:../lab_09/lab_09.adoc[Lab 9], so you can choose to continue with that project if you like): 
+
----
$ cd $COURSE_HOME/day_01/session_03/lab_10/initial/quotes
----

. At present we're still using the in-memory database. Let's connect to a MySQL database service.
From the CLI, let's _create_ a MySQL service instance:
+
[source,bash]
----
$ cf cs p-mysql 100mb-dev quotes-db
Creating service quotes-db...
OK
----
+
Again, if `p-mysql` service is not available, please use the free `spark` plan from `cleardb` like this `cf cs cleardb spark quotes-db`.

. Next add the service to your application manifest, which will _bind_ the service to our application on the next push. We'll also add an environment variable to switch on the ``cloud'' profile,
+
[source,yml]
----
---
applications:
- name: companies
  memory: 512M
  instances: 1
  path: target/quotes-1.0.0.jar
  timeout: 180
  services:                        # Add
  - quotes-db                      # these
  env:                             # four
    SPRING_PROFILES_ACTIVE: cloud  # lines
----
+
You can also accomplish the service binding by explicitly binding the service at the command-line:
+
[source,bash]
----
$ cf bind-service companies quotes-db
Binding service quotes-db to app companies...
OK
----

. Next we'll add Spring Cloud and MySQL dependencies to our maven pom file. Just after the dependency declaration for +h2+, add add the following in the +dependencies+ section:
+
[source,xml]
----

	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-spring-service-connector</artifactId>
		<version>1.2.0.RELEASE</version>
	</dependency>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-cloudfoundry-connector</artifactId>
		<version>1.2.0.RELEASE</version>
	</dependency>
	<dependency>
		<groupId>org.mariadb.jdbc</groupId>
		<artifactId>mariadb-java-client</artifactId>
		<version>1.3.2</version>
	</dependency>
	

----
+
Since we've added new dependencies, re-run +mvn clean package+ to build your project and download them.  If you are using an IDE, you will need to bring it up to date.  In Eclipse or STS you will need to right-click on the project and select Maven -> Update Project.

. Next, let's create the package +io.pivotal.demo.quotes.config+ and create in that package the class +CloudDataSourceConfig+. Add the following code:
+
[source,java]
----
@Profile("cloud")
@Configuration
public class CloudDataSourceConfig extends AbstractCloudConfig {
    @Bean
    public DataSource dataSource() {
        return connectionFactory().dataSource();
    }
}
----
+
As before, have the IDE import the appropriate dependencies.
+
The +@Profile+ annotation will cause this class (which becomes Spring configuration when annotated as +@Configuration+) to be added to the configuration set because of the +SPRING_PROFILES_ACTIVE+ environment variable we added earlier. You can still run the application locally (with the default profile) using the embedded database.
+
With this code, Spring Cloud will detect a bound service that is compatible with +DataSource+, read the credentials, and then create a +DataSource+ as appropriate (it will throw an exception otherwise).

. Add the following to +src/main/resources/application.properties+ to cause Hibernate to create the database schema and import data at startup. This is done automatically for embedded databases, but not for a custom ++DataSource++. Other Hibernate native properties can be set in a similar fashion:
+
[source,java]
----
spring.jpa.hibernate.ddl-auto=create
----

. Build the application:
+
[source,bash]
----
$ mvn clean package
----

. Re-push the application:
+
[source,bash]
----
$ cf push
----

. Take a look at the +env+ endpoint again to see the service bound in +VCAP_SERVICES+:
+
[source,bash]
----
$ curl -i http://companies.app.apj.cloud.fe.pivotal.io/env
...
"vcap" : {
    "vcap.services.quotes-db.name" : "quotes-db",
    "vcap.application.limits.mem" : "1024",
    "vcap.services.quotes-db.label" : "p-mysql",
    "vcap.services.quotes-db.credentials.hostname" : "******",
    "vcap.services.quotes-db.tags[1]" : "relational",
    "vcap.services.quotes-db.plan" : "100mb-dev",
    "vcap.application.application_uris" : "companies.app.apj.cloud.fe.pivotal.io",
    "vcap.application.uris" : "companies.app.apj.cloud.fe.pivotal.io",
    "vcap.application.application_version" : "a5ba43ec-f6c3-4861-9a9e-648cfbbfa0cd",
    "vcap.application.space_name" : "development",
    "vcap.application.application_name" : "companies",
    "vcap.application.name" : "companies",
    "vcap.application.version" : "a5ba43ec-f6c3-4861-9a9e-648cfbbfa0cd",
    "vcap.services.quotes-db.credentials.name" : "******",
    "vcap.services.quotes-db.credentials.jdbcUrl" : "******",
    "vcap.application.application_uris[0]" : "companies.app.apj.cloud.fe.pivotal.io",
    "vcap.application.instance_id" : "fa18db7a-8fb8-4bc0-6b0d-f99973ec3b69",
    "vcap.application.space_id" : "5c67f234-4ccb-4890-943a-9151c2cec1b1",
    "vcap.services.quotes-db.tags" : "mysql,relational",
    "vcap.services.quotes-db.credentials.password" : "******",
    "vcap.application.limits.fds" : "16384",
    "vcap.application.application_id" : "526662d6-a7ff-4bef-9f57-42293f5e6ceb",
    "vcap.services.quotes-db.tags[0]" : "mysql",
    "vcap.application.uris[0]" : "companies.app.apj.cloud.fe.pivotal.io",
    "vcap.services.quotes-db.credentials.username" : "******",
    "vcap.application.port" : "8080",
    "vcap.application.instance_index" : "0",
    "vcap.services.quotes-db.credentials.port" : "******",
    "vcap.application.host" : "0.0.0.0",
    "vcap.services.quotes-db.credentials.uri" : "******",
    "vcap.application.limits.disk" : "1024",
...
----
The application is now running against a MySQL database.

== Customising the +DataSource+

. You can customize the database connection that Spring Cloud creates with a few lines of code. Change the +dataSource+ method in +CloudDataSourceConfig+ to add some pooling and connection configuration:
+
[source,java]
----
@Bean
public DataSource dataSource() {
    PooledServiceConnectorConfig.PoolConfig poolConfig =
            new PooledServiceConnectorConfig.PoolConfig(5, 200);

    DataSourceConfig.ConnectionConfig connectionConfig =
            new DataSourceConfig.ConnectionConfig("characterEncoding=UTF-8");
    DataSourceConfig serviceConfig = new DataSourceConfig(poolConfig, connectionConfig);

    return connectionFactory().dataSource("quotes-db", serviceConfig);
}
----

. Build the application:
+
[source,bash]
----
$ mvn clean package
----

. Re-push the application:
+
[source,bash]
----
$ cf push
----
