spring:
  profiles.active: local
  application:
     name: portfolio

---
spring:
  profiles: local

  jpa:
     hibernate:
        ddl-auto: update
server:
  port: 8081

quotes:
  url: http://localhost:8086

accounts:
  url: http://localhost:8082

---
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update
quotes:
  url: http://quotes-undespising-lenition.cfapps.pez.pivotal.io

accounts:
  url: http://accounts-recompensatory-assassinator.cfapps.pez.pivotal.io

---