:compat-mode:
= Lab 13 - Build a Portfolio with MySQL

[abstract]
--
In this lab we'll begin the second subproject of our complete cloud-native application architecture: _SpringTrader_, which implements the quotes fetching portion of a ``Trading-like'' application.
This microservice will provide the _Portfolio Service_, which will allow us to see our trading transactions and assets.

--

NOTE: The completed code for this lab can be found at `$COURSE_HOME/day_01/session_05/lab_13/complete/springtrader-portfolio`.

== Developing the Service

. Change to the lab directory:
+
----
$ cd $COURSE_HOME/day_01/session_05/lab_13/initial/springtrader-portfolio
----
+
and import the project (via `pom.xml`) into your IDE of choice.

. Create the package `io.springtrader.portfolio.domain` and in that package create the class `Order`. Into that file you can paste the following source code:
+
----
@Entity
@Table(name = "ORDERS")
public class Order {

	@Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    @Column(name = "orderid")
	private Integer orderId;

	@Column(name = "accountid")
	@NotNull
	private String accountId;
	
	@Column(name = "symbol", length = 10)
	@NotNull
	private String symbol;

	@Column(name = "orderfee", precision = 14, scale = 2)
	private BigDecimal orderFee;

	@Column(name = "completiondate")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "LL")
	private Date completionDate;

	@Column(name = "ordertype")
	@NotNull
	@Enumerated
	private OrderType orderType;

	@Column(name = "price", precision = 14, scale = 2)
	@NotNull
	private BigDecimal price;

	@Column(name = "quantity")
	@NotNull
	private Integer quantity;

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public String getAccountId() {
		return accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public BigDecimal getOrderFee() {
		return orderFee;
	}

	public void setOrderFee(BigDecimal orderFee) {
		this.orderFee = orderFee;
	}

	public Date getCompletionDate() {
		return completionDate;
	}

	public void setCompletionDate(Date completionDate) {
		this.completionDate = completionDate;
	}

	public OrderType getOrderType() {
		return orderType;
	}

	public void setOrderType(OrderType orderType) {
		this.orderType = orderType;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Order [orderId=").append(orderId)
				.append(", accountId=").append(accountId).append(", symbol=")
				.append(symbol).append(", orderFee=").append(orderFee)
				.append(", completionDate=").append(completionDate)
				.append(", orderType=").append(orderType).append(", price=")
				.append(price).append(", quantity=").append(quantity)
				.append("]");
		return builder.toString();
	}
}
----

. In the same package create the class `Quote`. Into that file you can paste the following source code:

+
----
@JsonIgnoreProperties(ignoreUnknown = true)
public class Quote {

	@JsonProperty("Status")
	private String status;
	@JsonProperty("Name")
	private String name;
	@JsonProperty("Symbol")
	private String symbol;
	@JsonProperty("LastPrice")
	private Double lastPrice;
	@JsonProperty("Change")
	private Double change;
	@JsonProperty("ChangePercent")
	private Double changePercent;
	@JsonProperty("Timestamp")
	@JsonFormat(shape= JsonFormat.Shape.STRING, pattern="EEE MMM dd HH:mm:ss zzzXXX yyyy")
	private Date timestamp;
	@JsonProperty("MSDate")
	private Double mSDate;
	@JsonProperty("MarketCap")
	private Double marketCap;
	@JsonProperty("Volume")
	private Integer volume;
	@JsonProperty("ChangeYTD")
	private Double changeYTD;
	@JsonProperty("ChangePercentYTD")
	private Double changePercentYTD;
	@JsonProperty("High")
	private Double high;
	@JsonProperty("Low")
	private Double low;
	@JsonProperty("Open")
	private Double open;
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}
	public Double getLastPrice() {
		return lastPrice;
	}

	public void setLastPrice(Double lastPrice) {
		this.lastPrice = lastPrice;
	}
	public Double getChangePercent() {
		return changePercent;
	}

	public void setChangePercent(Double changePercent) {
		this.changePercent = changePercent;
	}
	public Date getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}
	public Double getmSDate() {
		return mSDate;
	}

	public void setmSDate(Double mSDate) {
		this.mSDate = mSDate;
	}
	public Double getMarketCap() {
		return marketCap;
	}

	public void setMarketCap(Double marketCap) {
		this.marketCap = marketCap;
	}
	public Integer getVolume() {
		return volume;
	}

	public void setVolume(Integer volume) {
		this.volume = volume;
	}
	public Double getChangeYTD() {
		return changeYTD;
	}

	public void setChangeYTD(Double changeYTD) {
		this.changeYTD = changeYTD;
	}
	public Double getChangePercentYTD() {
		return changePercentYTD;
	}

	public void setChangePercentYTD(Double changePercentYTD) {
		this.changePercentYTD = changePercentYTD;
	}
	public Double getHigh() {
		return high;
	}

	public void setHigh(Double high) {
		this.high = high;
	}
	public Double getLow() {
		return low;
	}

	public void setLow(Double low) {
		this.low = low;
	}
	public Double getOpen() {
		return open;
	}

	public void setOpen(Double open) {
		this.open = open;
	}

	public Double getChange() {
		return change;
	}

	public void setChange(Double change) {
		this.change = change;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}
----
. Create the class `Holding`. It represents a holding, a set of orders related to a particular stock. Into that file you can paste the following source code:
+
----
public class Holding {

	private Integer id;

	private String symbol;

	private Integer quantity = 0;

	private BigDecimal purchaseValue = BigDecimal.ZERO;

	private BigDecimal sellValue = BigDecimal.ZERO;

	private Set<Order> orders = new HashSet<>();

	private BigDecimal currentValue = BigDecimal.ZERO;

    public Integer getId() {
		return id;
	}

    public void setId(Integer id) {
		this.id = id;
	}
    public String getSymbol() {
		return symbol;
	}
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}
	public Integer getQuantity() {
		return quantity;
	}
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	public BigDecimal getPurchaseValue() {
		return purchaseValue;
	}
	public void setPurchaseValue(BigDecimal purchaseValue) {
		this.purchaseValue = purchaseValue;
	}
	public Set<Order> getOrders() {
		return orders;
	}
	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}
	public BigDecimal getCurrentValue() {
		return currentValue;
	}
	public void setCurrentValue(BigDecimal currentValue) {
		this.currentValue = currentValue;
	}

	public void addOrder(Order order) {
		//check order is not already in.
		if (!orders.contains(order)) {
			orders.add(order);
			//update stats
			if (order.getOrderType().equals(OrderType.BUY)) {

				setQuantity(getQuantity() + order.getQuantity());
				setPurchaseValue(getPurchaseValue().add(order.getPrice().multiply(new BigDecimal(order.getQuantity()))));

			} else if (order.getOrderType().equals(OrderType.SELL)) {

				setQuantity(getQuantity() - order.getQuantity());
				setSellValue(getSellValue().add(order.getPrice().multiply(new BigDecimal(order.getQuantity()))));

			}
		}
	}

	public BigDecimal getSellValue() {
		return sellValue;
	}
	public void setSellValue(BigDecimal sellPrice) {
		this.sellValue = sellPrice;
	}
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Holding [id=").append(id).append(", symbol=")
				.append(symbol).append(", quantity=").append(quantity)
				.append(", purchasePrice=").append(purchaseValue)
				.append(", sellPrice=").append(sellValue).append(", orders=")
				.append(orders).append(", currentValue=").append(currentValue)
				.append("]");
		return builder.toString();
	}
}
----

. Create the class `Portfolio`. Portfolios are a collection of holdings. Into that file you can paste the following source code:
+
----
public class Portfolio {

    private String accountId;

    private String name;

    private BigDecimal currentTotalValue = BigDecimal.ZERO;

    private BigDecimal purchaseValue = BigDecimal.ZERO;

    private BigDecimal sellValue = BigDecimal.ZERO;

    private Map<String, Holding> holdings = new HashMap<>();

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Map<String, Holding> getHoldings() {
        return holdings;
    }

    public void setHoldings(Map<String, Holding> holdings) {
        this.holdings = holdings;
    }

    public void addHolding(Holding holding) {
        holdings.put(holding.getSymbol(), holding);
    }

    public Holding getHolding(String symbol) {
        return holdings.get(symbol);
    }

    public BigDecimal getCurrentTotalValue() {
        return currentTotalValue;
    }

    public void setCurrentTotalValue(BigDecimal currentTotalValue) {
        this.currentTotalValue = currentTotalValue;
    }

    /**
     * Iterates through each of the holdings aggregating the values.
     */
    public void refreshTotalValue() {
        this.currentTotalValue = BigDecimal.ZERO;
        this.purchaseValue = BigDecimal.ZERO;
        this.sellValue = BigDecimal.ZERO;
        holdings.values().forEach(holding -> {
            this.currentTotalValue = this.currentTotalValue.add(holding.getCurrentValue().multiply(new BigDecimal(holding.getQuantity())));
            this.purchaseValue = this.purchaseValue.add(holding.getPurchaseValue());
            this.sellValue = this.sellValue.add(holding.getSellValue());
        });
    }

    public BigDecimal getSellValue() {
        return sellValue;
    }

    public void setSellValue(BigDecimal sellValue) {
        this.sellValue = sellValue;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Portfolio [accountId=").append(accountId)
                .append(", name=").append(name).append(", currentTotalValue=")
                .append(currentTotalValue).append(", purchaseValue=")
                .append(purchaseValue).append(", sellValue=").append(sellValue)
                .append(", holdings=").append(holdings).append("]");
        return builder.toString();
    }

    public BigDecimal getPurchaseValue() {
        return purchaseValue;
    }

    public void setPurchaseValue(BigDecimal purchaseValue) {
        this.purchaseValue = purchaseValue;
    }

}
----

. Create the package `io.springtrader.portfolio.repositories` and in that package create the interface `OrderRepository`. Into that file you can paste the following source code:
+
----
public interface OrderRepository extends CrudRepository<Order,Integer> {
	List<Order> findByAccountId(String accountId);
}
----

. Create the package `io.springtrader.portfolio.repositories` and in that package create the interface `OrderRepository`. Into that file you can paste the following source code:
+
----
public interface OrderRepository extends CrudRepository<Order,Integer> {
	List<Order> findByAccountId(String accountId);
}
----

. Create the package `io.springtrader.portfolio.services` and in that package create the interface `PortfolioService`. Into that file you can paste the following source code:
+
----
@Service
public class PortfolioService {

	private static final Logger logger = LoggerFactory.getLogger(PortfolioService.class);


	@Autowired
	OrderRepository repository;

	@Autowired
	private RestTemplate restTemplate;

	public Portfolio getPortfolio(String accountId) {
		/*
		 * Retrieve all orders for accounts id and build portfolio.
		 * - for each order create holding.
		 * - for each holding find current price.
		 */
		logger.debug("Getting portfolio for accountId: " + accountId);
		List<Order> orders = repository.findByAccountId(accountId);
		return createPortfolio(new Portfolio(), orders);
	}


	private Portfolio createPortfolio(Portfolio portfolio, List<Order> orders) {
		//TODO: change to forEach() and maybe in parallel?
		for (Order order: orders) {
			Holding holding = portfolio.getHolding(order.getSymbol());
			if ( holding == null) {
				holding = new Holding();
				holding.setSymbol(order.getSymbol());
				portfolio.addHolding(holding);
			}
			holding.addOrder(order);
		}

		// getLatestQuotes in parallel
		portfolio.getHoldings().values().parallelStream().forEach(holding -> refreshHolding(holding));
		portfolio.refreshTotalValue();
		logger.debug("Portfolio: " + portfolio);
		return portfolio;
	}

	/**
	 * Calculates the current value of th holding.
	 *
	 * @param holding the holding to refresh.
	 */
	private void refreshHolding(Holding holding) {
		Quote quote = getQuote(holding.getSymbol());
		holding.setCurrentValue(new BigDecimal(quote.getLastPrice()));
	}


	private Quote getQuote(String symbol) {
		logger.debug("Fetching quote: " + symbol);
		Quote quote = restTemplate.getForObject("http://localhost:8086/quote/{symbol}", Quote.class, symbol);
		return quote;
	}


	@Transactional
	public Order addOrder(Order order) {
		logger.debug("Adding order: " + order);
		if (order.getOrderFee() == null) {
			order.setOrderFee(new BigDecimal(10.50));
			logger.debug("Adding Fee to order: " + order);
		}
		if (order.getOrderType() == OrderType.BUY) {
			double amount = order.getQuantity()*order.getPrice().doubleValue()+order.getOrderFee().doubleValue();
			ResponseEntity<Double> result= restTemplate.getForEntity("http://localhost:8081/accounts/{userid}/decreaseBalance/{amount}", Double.class, order.getAccountId(), amount);
			return saveOrder(order, result);
		} else {
			double amount = order.getQuantity()*order.getPrice().doubleValue()-order.getOrderFee().doubleValue();
			ResponseEntity<Double> result= restTemplate.getForEntity("http://localhost:8081/accounts/{userid}/increaseBalance/{amount}", Double.class, order.getAccountId(), amount);
			return saveOrder(order,result);
		}


	}

	private Order saveOrder(Order order, ResponseEntity<Double> result) {
		if (result.getStatusCode() == HttpStatus.OK) {
            logger.info(String.format("Account funds updated successfully for account: %s and new funds are: %s", order.getAccountId(), result.getBody()));
            return repository.save(order);
        } else {
            //TODO: throw exception - not enough funds!
            logger.warn("PortfolioService:addOrder - decresing balance HTTP not ok: ");
            return null;
        }
	}
}
----

. Create the package `io.springtrader.portfolio.controllers` and in that package create the interface `PortfolioController`. Into that file you can paste the following source code:
+
----
@RestController
public class PortfolioController {

	private static final Logger logger = LoggerFactory.getLogger(PortfolioController.class);


	@Autowired
	private PortfolioService service;


	@RequestMapping(value = "/portfolio/{id}", method = RequestMethod.GET)
	public ResponseEntity<Portfolio> getPortfolio(@PathVariable("id") final String accountId) {
		logger.debug("PortfolioController: Retrieving portfolio with user id:" + accountId);
		Portfolio folio = service.getPortfolio(accountId);
		logger.debug("PortfolioController: Retrieved portfolio:" + folio);
		return new ResponseEntity<>(folio, getNoCacheHeaders(), HttpStatus.OK);
	}

	private HttpHeaders getNoCacheHeaders() {
		HttpHeaders responseHeaders = new HttpHeaders();
		responseHeaders.set("Cache-Control", "no-cache");
		return responseHeaders;
	}

	@RequestMapping(value = "/portfolio/{id}", method = RequestMethod.POST)
	public ResponseEntity<Order> addOrder(@PathVariable("id") final String accountId, @RequestBody final Order order, UriComponentsBuilder builder) {
		logger.debug("Adding Order: " + order);

		//TODO: can do a test to ensure accountId == order.getAccountId();

		Order savedOrder = service.addOrder(order);
		HttpHeaders responseHeaders = new HttpHeaders();
		responseHeaders.setLocation(builder.path("/portfolio/{id}")
				.buildAndExpand(accountId).toUri());
		logger.debug("Order added: " + savedOrder);
		if (savedOrder != null && savedOrder.getOrderId() != null) {
			return new ResponseEntity<Order>(savedOrder, responseHeaders, HttpStatus.CREATED);
		} else {
			logger.warn("Order not saved: " + order);
			return new ResponseEntity<Order>(savedOrder, responseHeaders, HttpStatus.INTERNAL_SERVER_ERROR);
		}
	}
}
----

. Add the `@EnableJpaRepositories` annotation to `io.springtrader.portfolio.PortfolioApplication`:
+
----
@SpringBootApplication
@EnableJpaRepositories <--- Add this!!
public class PortfolioApplication {

    public static void main(String[] args) {
        SpringApplication.run(PortfolioApplication.class, args);
    }
}
----

. Add the following to `application.yml` -- we'll eventually want to run multiple apps locally, so we need to change the port:
+
----
spring:
  profiles.active: local
  application:
     name: portfolio

---
spring:
  profiles: local
  jpa:
     hibernate:
        ddl-auto: update
server:
  port: 8081
---
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update
----

. To run the application locally, you'll need either in-memory H2 database or a local installation MySQL/Postgres. To run against in-memory H2 locally add
the following to your `pom.xml` file. If run locally with the default setup, the application will automatically discover it and connect to it.

+
----
 <dependency>
	<groupId>com.h2database</groupId>
  	<artifactId>h2</artifactId>
    <scope>runtime</scope>
 </dependency>
----

. Build the JAR:
+
----
$ mvn clean package
----

. Run the application:
+
----
$ java -jar target/portfolio-1.0.0-SNAPSHOT.jar
----

. Run the following script to insert data via the application's API. Make sure you have the previous Account and Quotes services up and running.
+
----
$ scripts/loadAccounts.sh
$ scripts/loadOrders.sh
----

. Access the application using `curl` to make sure everything is working properly:
+
----
$ curl -i http://localhost:8081/portfolio/johndoe
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Tue, 08 Dec 2015 09:21:52 GMT

{"accountId":null,"name":null,"currentTotalValue":255.4500000000000170530256582424044609069824218750,
"purchaseValue":100.00,"sellValue":0,"holdings":{"EMC":{"id":null,"symbol":"EMC","quantity":10,
"purchaseValue":100.00,"sellValue":0,"orders":[{"orderId":1,"accountId":"johndoe","symbol":"EMC",
"orderFee":1.00,"completionDate":1329759342904,"orderType":"BUY","price":10.00,"quantity":10}],
"currentValue":25.5450000000000017053025658242404460906982421875}}}
----

== Preparing for Cloud Foundry


. We want to bind to a MongoDB data source when running on Cloud Foundry, so let's create one:
+
----
$ cf cs p-mysql 100mb-dev springtrader-portfolio-db
Creating service instance springtrader-portfolio-db in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK
----

. Add the appropriate dependencies for the Spring Cloud Connectors:
+
----
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-cloudfoundry-connector</artifactId>
</dependency>
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-spring-service-connector</artifactId>
</dependency>
----

. Build the JAR:
+
----
$ mvn clean package
----

== Deploying to Cloud Foundry

. Create an application manifest in `manifest.yml`:
+
[source,yml]
----
timeout: 180
instances: 1
memory: 512M
env:
    SPRING_PROFILES_ACTIVE: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: portfolio
  random-route: true
  path: target/portfolio-1.0.0-SNAPSHOT.jar
  services: [ springtrader-portfolio-db ]
----
. Before push to Cloud Foundry adjuste the application.yml (cloud profile) file with the URLs for the Accounts and Quotes services. Something like:
+
----
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update

quotes:
  url: http://quotes-undespising-lenition.cfapps.pez.pivotal.io

accounts:
  url: http://accounts-recompensatory-assassinator.cfapps.pez.pivotal.io
----

. Push to Cloud Foundry:
+
----
$ cf push

...

----

. Run the load script with the `ROUTE` environment variable set to the random route generated by CF to insert data via the application's API:
+
----
$ ROUTE=portfolio.cfapps.pez.pivotal.io  loadAccounts.sh
$ ROUTE=portfolio.cfapps.pez.pivotal.io  loadOrders.sh
----

. Access the application using `curl` to make sure everything is working properly:
+
----
$ curl -i portfolio.cfapps.pez.pivotal.io/portfolio/johndoe
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Tue, 08 Dec 2015 09:21:52 GMT

{"accountId":null,"name":null,"currentTotalValue":255.4500000000000170530256582424044609069824218750,
"purchaseValue":100.00,"sellValue":0,"holdings":{"EMC":{"id":null,"symbol":"EMC","quantity":10,
"purchaseValue":100.00,"sellValue":0,"orders":[{"orderId":1,"accountId":"johndoe","symbol":"EMC",
"orderFee":1.00,"completionDate":1329759342904,"orderType":"BUY","price":10.00,"quantity":10}],
"currentValue":25.5450000000000017053025658242404460906982421875}}}
----
