= Lab 3 - Externalizing Configuration with Spring Boot

== Refactoring to Externalize the Config

. Change to the lab directory (or continue to build off of lab_01 or lab_02):
+
----
$ cd $COURSE_HOME/day_01/session_01/lab_03/initial/hello-spring-boot
----

. Import the project's `pom.xml` into your editor/IDE of choice (if you haven't in a previous lab).

. Open `src/main/resources/application.yml` and paste the following:
+
----
greeting: Hello
----

. To the class `io.pivotal.spring.hello.HelloSpringBootApplication`, add a `greeting` field and inject its value:
+
----
@Value("${greeting}")
String greeting;
----

. Also `io.pivotal.spring.hello.HelloSpringBootApplication`, change the return statement of `hello()` to the following:
+
----
return String.format("%s World!", greeting);
----

. Run the application
+
You can run it within your IDE or use the below command:
+
----
$ mvn package
$ java -jar target/lab03-hello-spring-boot-0.0.1-SNAPSHOT.jar
----

. Visit the application in the browser (http://localhost:8080), and verify that the output is still the following:
+
----
Hello World!
----

. Stop the application.

== Using Environment Variables for Config

. Run the application again, this time setting the `GREETING` environment variable:
+
----
Linux, MacOS:
$ GREETING=Ohai java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar

Windows:
> set GREETING=Ohai && java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar
----

. Visit the application in the browser (http://localhost:8080), and verify that the output has changed to the following:
+
----
Ohai World!
----

. Stop the application.

== Using Spring Profiles for Config

. Add a `spanish` profile to `application.yml`. Your finished configuration should reflect the following:
+
----
greeting: Hello

---

spring:
  profiles: spanish

greeting: Hola
----

. Build the application:
+
----
$ mvn package
----

. Run the application, this time setting the `SPRING_PROFILES_ACTIVE` environment variable:
+
----
Linux, MacOS:
$ SPRING_PROFILES_ACTIVE=spanish java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar

Windows:
$ set GREETING=
$ set SPRING_PROFILES_ACTIVE=spanish && java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar

----

. Visit the application in the browser (http://localhost:8080), and verify that the output has changed to the following:
+
----
Hola World!
----

. Visit http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html to learn more about this outcome and the entire priority scheme for conflict resolution.
